project:
  type: website
 
website:
  title: "Penguins Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: model_basic.qmd
        text: Model
    right:
      - href: eda_db.qmd
        text: Visual
 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
 
editor: visual

